/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_cxria_myapplication_CCallNative */

#ifndef _Included_com_cxria_myapplication_CCallNative
#define _Included_com_cxria_myapplication_CCallNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_cxria_myapplication_CCallNative
 * Method:    hello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_cxria_myapplication_CCallNative_hello
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
